"""empty message

Revision ID: 758af2cc0f15
Revises: 92efd55a5505
Create Date: 2020-03-17 08:09:02.675042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758af2cc0f15'
down_revision = '92efd55a5505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'audience', 'thing', ['id'], ['id'])
    op.create_foreign_key(None, 'credit_card', 'thing', ['id'], ['id'])
    op.create_foreign_key(None, 'customer_address', 'thing', ['id'], ['id'])
    op.create_foreign_key(None, 'customer_data', 'thing', ['id'], ['id'])
    op.create_foreign_key(None, 'event', 'event', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'event', 'thing', ['id'], ['id'])
    op.create_foreign_key(None, 'event', 'audience', ['audience_id'], ['id'])
    op.create_foreign_key(None, 'event_offer', 'event', ['event_id'], ['id'])
    op.create_foreign_key(None, 'event_offer', 'offer', ['offer_id'], ['id'])
    op.create_foreign_key(None, 'line_item', 'transaction_request', ['transaction_request_id'], ['id'])
    op.create_foreign_key(None, 'line_item', 'thing', ['id'], ['id'])
    op.create_foreign_key(None, 'offer', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'offer', 'thing', ['id'], ['id'])
    op.create_foreign_key(None, 'order', 'thing', ['id'], ['id'])
    op.create_foreign_key(None, 'payment', 'credit_card', ['credit_card_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'thing', ['id'], ['id'])
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'post', 'thing', ['thing_id'], ['id'])
    op.create_foreign_key(None, 'price_specification', 'thing', ['id'], ['id'])
    op.create_foreign_key(None, 'price_specification', 'offer', ['offer_id'], ['id'])
    op.create_foreign_key(None, 'product', 'price_specification', ['price_specification_id'], ['id'])
    op.create_foreign_key(None, 'product', 'thing', ['id'], ['id'])
    op.create_foreign_key(None, 'reservation', 'event', ['reservation_for_id'], ['id'])
    op.create_foreign_key(None, 'reservation', 'thing', ['id'], ['id'])
    op.create_foreign_key(None, 'reservation', 'transaction_request', ['transaction_request_id'], ['id'])
    op.create_foreign_key(None, 'transaction_request', 'transaction_response', ['transaction_response_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_request', type_='foreignkey')
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'price_specification', type_='foreignkey')
    op.drop_constraint(None, 'price_specification', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.drop_constraint(None, 'line_item', type_='foreignkey')
    op.drop_constraint(None, 'line_item', type_='foreignkey')
    op.drop_constraint(None, 'event_offer', type_='foreignkey')
    op.drop_constraint(None, 'event_offer', type_='foreignkey')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_constraint(None, 'customer_data', type_='foreignkey')
    op.drop_constraint(None, 'customer_address', type_='foreignkey')
    op.drop_constraint(None, 'credit_card', type_='foreignkey')
    op.drop_constraint(None, 'audience', type_='foreignkey')
    # ### end Alembic commands ###
