"""empty message

Revision ID: 92efd55a5505
Revises: 
Create Date: 2020-03-17 08:02:44.847323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92efd55a5505'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audience_type', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('card_code', sa.String(length=8), nullable=True),
    sa.Column('expiration_date', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=256), nullable=True),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('zip', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('door_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('maximum_attendee_capacity', sa.Integer(), nullable=True),
    sa.Column('audience_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('calendar_code', sa.String(length=16), nullable=True),
    sa.Column('primary_image', sa.String(length=128), nullable=True),
    sa.Column('secondary_image', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_basic', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_door_time'), 'event', ['door_time'], unique=False)
    op.create_index(op.f('ix_event_end_time'), 'event', ['end_time'], unique=False)
    op.create_index(op.f('ix_event_start_time'), 'event', ['start_time'], unique=False)
    op.create_table('event_offer',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    )
    op.create_table('line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_request_id', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.String(length=128), nullable=True),
    sa.Column('availability_starts', sa.DateTime(), nullable=True),
    sa.Column('availability_ends', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('offer_code', sa.String(length=16), nullable=True),
    sa.Column('inventory_level', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_availability_ends'), 'offer', ['availability_ends'], unique=False)
    op.create_index(op.f('ix_offer_availability_starts'), 'offer', ['availability_starts'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=32), nullable=True),
    sa.Column('credit_card_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thing_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('price_specification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('flat_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_fee', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.Column('logo', sa.String(length=256), nullable=True),
    sa.Column('model', sa.String(length=256), nullable=True),
    sa.Column('price_specification_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_time', sa.DateTime(), nullable=True),
    sa.Column('reservation_for_id', sa.Integer(), nullable=True),
    sa.Column('under_name', sa.String(length=256), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transaction_request_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('uuid', sa.String(length=64), nullable=True),
    sa.Column('alternate_name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('disambiguating_description', sa.String(length=1024), nullable=True),
    sa.Column('identifier', sa.String(length=256), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('main_entity_of_page', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('ip_address', sa.String(length=32), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=64), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['id'], ['thing.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_address_id', sa.Integer(), nullable=True),
    sa.Column('customer_data_id', sa.Integer(), nullable=True),
    sa.Column('transaction_response_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_address_id'], ['customer_address.id'], ),
    sa.ForeignKeyConstraint(['customer_data_id'], ['customer_data.id'], ),
    sa.ForeignKeyConstraint(['id'], ['thing.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.String(length=16), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['thing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('transaction_response')
    op.drop_table('transaction_request')
    op.drop_table('ticket')
    op.drop_table('thing')
    op.drop_table('reservation')
    op.drop_table('product')
    op.drop_table('price_specification')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('payment')
    op.drop_table('order')
    op.drop_index(op.f('ix_offer_availability_starts'), table_name='offer')
    op.drop_index(op.f('ix_offer_availability_ends'), table_name='offer')
    op.drop_table('offer')
    op.drop_table('line_item')
    op.drop_table('event_offer')
    op.drop_index(op.f('ix_event_start_time'), table_name='event')
    op.drop_index(op.f('ix_event_end_time'), table_name='event')
    op.drop_index(op.f('ix_event_door_time'), table_name='event')
    op.drop_table('event')
    op.drop_table('customer_data')
    op.drop_table('customer_address')
    op.drop_table('credit_card')
    op.drop_table('audience')
    # ### end Alembic commands ###
